package com.codehealth.service;

import com.codehealth.dto.HealthReportDto;
import com.codehealth.dto.RecommendationDto;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;

@Service
public class ExportService {

    public byte[] generateJsonReport(HealthReportDto report) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            mapper.registerModule(new JavaTimeModule());
            mapper.enable(SerializationFeature.INDENT_OUTPUT);
            String json = mapper.writeValueAsString(report);
            return json.getBytes(StandardCharsets.UTF_8);
        } catch (Exception e) {
            return "{}".getBytes();
        }
    }

    public byte[] generatePdfReport(HealthReportDto report) {
        StringBuilder sb = new StringBuilder();
        sb.append("%PDF-1.4\n");
        sb.append("1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n");
        sb.append("2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n");
        sb.append("3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >> endobj\n");
        sb.append("xref\n");
        sb.append("0 4\n");
        sb.append("0000000000 65535 f \n");
        sb.append("0000000009 00000 n \n");
        sb.append("0000000058 00000 n \n");
        sb.append("0000000115 00000 n \n");
        sb.append("trailer << /Size 4 /Root 1 0 R >>\n");
        sb.append("startxref\n");
        sb.append("190\n");
        sb.append("%%EOF\n");
        
        byte[] header = sb.toString().getBytes(StandardCharsets.UTF_8);
        byte[] content = generatePdfContent(report).getBytes(StandardCharsets.UTF_8);
        byte[] footer = "\n%%EOF\n".getBytes(StandardCharsets.UTF_8);
        
        byte[] pdf = new byte[header.length + content.length + footer.length];
        System.arraycopy(header, 0, pdf, 0, header.length);
        System.arraycopy(content, 0, pdf, header.length, content.length);
        System.arraycopy(footer, 0, pdf, header.length + content.length, footer.length);
        
        return pdf;
    }

    private String generatePdfContent(HealthReportDto report) {
        return String.format("""
            %% Code Health Checker Report
            %% Generated: %s
            
            HEALTH REPORT
            =============
            Overall Score: %d/100
            
            DIMENSION SCORES
            ----------------
            Coverage: %d%%
            Complexity: %d%%
            Duplication: %d%%
            Documentation: %d%%
            Security: %d%%
            Maintainability: %d%%
            
            METRICS
            -------
            Total Lines: %d
            Files Analyzed: %d
            Critical Issues: %d
            Major Issues: %d
            Minor Issues: %d
            
            TOP RECOMMENDATIONS
            -------------------
            %s
            
            Generated by Code Health Checker
            """,
            report.getCreatedAt(),
            report.getOverallScore(),
            report.getCoverageScore(),
            report.getComplexityScore(),
            report.getDuplicationScore(),
            report.getDocumentationScore(),
            report.getSecurityScore(),
            report.getMaintainabilityScore(),
            report.getTotalLines(),
            report.getFilesAnalyzed(),
            report.getCriticalIssues(),
            report.getMajorIssues(),
            report.getMinorIssues(),
            report.getRecommendations().stream()
                .limit(5)
                .map(r -> r.getPriority() + ". " + r.getTitle())
                .reduce("", (a, b) -> a + "\n" + b)
        );
    }
}